; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    nrf24/RF24 @ ^1.4.9
    Wire
    Servo
    SPI

build_flags = -I$PROJECT_SRC_DIR -I$PROJECT_LIB_DIR

upload_speed = 115200
monitor_speed = 115200
